import { Contact2 } from "@/components/blocks/contact-2";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Page = () => {
  return (
    <>
      <Contact2
        title="Nous contactez"
        description="Nous sommes disponibles pour répondre à vos questions, recueillir vos retours ou étudier toute opportunité de collaboration. Dites-nous comment nous pouvons vous aider !"
        phone="+ 33 7 57 83 71 10"
        email="email@example.com"
      />
    </>
  );
};

export default Page;
