import IconConfiguration from "@/components/svg/IconConfiguration";
import IconDeployement from "@/components/svg/IconDeployement";
import IconDesign from "@/components/svg/IconDesign";
import IconPages from "@/components/svg/IconPages";
import IconSeo from "@/components/svg/IconSeo";
import IconTraining from "@/components/svg/IconTraining";
import SiteVitrineExplication from "@/public/images/site-vitrine/captive-web_site_vitrine_explication.png";
import SiteVitrineIntro from "@/public/images/site-vitrine/captive-web_site_vitrine_introduction.png";
import SiteVitrinePresentation from "@/public/images/site-vitrine/captive-web_site_vitrine_presentation.png";
import SiteProfessionnels from "@/public/images/site-vitrine/captive-web_site_web_professionnels.png";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { GrTools } from "react-icons/gr";
import { IoStorefrontOutline } from "react-icons/io5";
import { MdOutlineHealthAndSafety } from "react-icons/md";
import { RiWhatsappFill } from "react-icons/ri";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Page() {
  return (
    <>
      <section className="pt-10 lg:pt-2 bg-captive-primary px-8 lg:px-32">
        <div className="container grid lg:grid-cols-2 gap-y-4 lg:gap-y-0 lg:place-content-between">
          <div className="place-self-center">
            <h1 className="heading__page">
              Gagnez en visibilité et en confiance avec un site web clé en main
            </h1>
            <p className="text-lg text-center lg:text-left">
              Plus qu’un simple site, nous créons un outil de communication
              efficace pour valoriser votre activité et générer des
              opportunités.
            </p>
          </div>
          <div className="flex justify-end">
            <Image
              src={SiteVitrinePresentation}
              alt="Captive web création site e-commerce"
              className="lg:w-[70%]"
              style={{
                maxWidth: "100%",
                height: "auto",
              }}
              priority
            />
          </div>
        </div>
      </section>
      <section className="py-16 px-8 lg:px-32">
        <div className="grid lg:grid-cols-2 lg:gap-x-10 gap-y-4 lg:items-center">
          <Image
            src={SiteVitrineIntro}
            alt="Illustration site web e-commerce"
            className="justify-self-center place-self-center rounded-lg order-2 lg:order-1"
            width={800}
            height={800}
            style={{
              maxWidth: "90%",
              height: "auto",
            }}
            priority
          />

          <div className="order-1 lg:order-2">
            <h2 className="mb-6">
              Un site web professionnel sans prise de tête
            </h2>
            <p>
              Vous êtes artisan, commerçant local, indépendant ou à la tête
              d’une petite entreprise ? Vous savez que la présence en ligne est
              aujourd’hui essentielle pour gagner en visibilité, rassurer vos
              clients et développer votre activité, mais vous ne savez pas par
              où commencer ?
            </p>
            <p>
              Nous concevons pour vous un site vitrine professionnel, clair,
              moderne et adapté à votre métier. Notre objectif : vous livrer un
              site web, efficace pour votre communication, et fidèle à l’image
              que vous souhaitez transmettre.
            </p>
          </div>
        </div>
        <div className="grid lg:grid-cols-2 lg:gap-x-10 gap-y-4 lg:items-center mt-10">
          <div className="place-self-center order-1">
            <h2 className="mb-6">
              Que vous vendiez un service, un savoir-faire ou votre expertise :
              soyez visible
            </h2>
            <p>
              Un site vitrine est idéal pour toutes les entreprises ou
              professionnels qui souhaitent présenter leurs services, renforcer
              leur crédibilité et être trouvés sur Google, sans forcément vendre
              en ligne.
            </p>
            <p>
              Avec un site vitrine, chaque visite peut devenir une opportunité.
              Grâce à des formulaires intégrés, vos visiteurs peuvent demander
              un devis, réserver un rendez-vous ou vous contacter facilement, en
              quelques clics. Vos prospects trouvent les informations qu’ils
              cherchent et peuvent vous joindre facilement. Vous gagnez du temps
              et transformez plus de visiteurs en clients.
            </p>
            <p>
              Que vous exerciez seul ou en équipe, votre site devient votre
              carte de visite digitale accessible 24h/24.
            </p>
          </div>
          <Image
            src={SiteVitrineExplication}
            alt="Logo Shopify"
            className="justify-self-center place-self-center order-2 lg:w-[80%]"
            width={800}
            height={800}
            style={{
              maxWidth: "100%",
              height: "auto",
            }}
            priority
          />
        </div>
      </section>
      <section className="py-16 px-8 lg:px-32 bg-captive-primary">
        <div className="flex items-center flex-col">
          <span className="heading__span">
            SITE WEB PRO
          </span>
          <h2 className="heading__center">
            Un site web vitrine : pour qui ?
          </h2>
        </div>
        <div className="grid lg:grid-cols-2 gap-y-12 lg:gap-y-0 items-center">
          <div>
            {/* <div className="grid lg:grid-cols-2 gap-x-10 gap-y-4">
              <ul className="flex flex-col gap-y-4">
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-start gap-x-2">
                     <FaCirclePlus className=" w-5 h-5 text-captive-blue mt-2" />
                     <div>
                      <h3 className="text-lg font-semibold">Artisans</h3>
                      <p className="mb-0">Plombier, électricien, maçon, peintre...</p>
                    </div>     
                  </div>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-start gap-x-2">
                     <FaCirclePlus className=" w-5 h-5 text-captive-blue mt-2" />
                     <div>
                      <h3 className="text-lg font-semibold">Commerçant local</h3>
                      <p className="mb-0">Restaurant, salon de coiffure, boutique,
                      fleuriste...</p>
                    </div>     
                  </div>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-start gap-x-2">
                     <FaCirclePlus className=" w-5 h-5 text-captive-blue mt-2" />
                     <div>
                      <h3 className="text-lg font-semibold">Profession libérale</h3>
                      <p className="mb-0">Avocat, médecin, architecte, consultant...</p>
                    </div>     
                  </div>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-start gap-x-2">
                     <FaCirclePlus className=" w-5 h-5 text-captive-blue mt-2" /> 
                     <div>
                      <h3 className="text-lg font-semibold">Indépendant / auto-entrepreneur</h3>
                      <p className="mb-0">Coach, photographe,
                      graphiste...</p>
                    </div>   
                  </div>
                </li>
              </ul>
              <ul className="flex flex-col gap-y-4">
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-start gap-x-2 ">
                     <FaCirclePlus className=" w-5 h-5 text-captive-blue mt-2" />
                     <div>
                      <h3 className="text-lg font-semibold">Professionnel du bien-être</h3>
                      <p className="mb-0">Ostéopathe, naturopathe,
                      esthéticienne,...</p>
                    </div>  
                  </div>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-start gap-x-2 ">
                     <FaCirclePlus className=" w-5 h-5 text-captive-blue mt-2" /> 
                     <div>
                      <h3 className="text-lg font-semibold">TPE / PME</h3>
                      <p className="mb-0">Souhaitant une présence professionnelle
                      en ligne</p>
                    </div>    
                  </div>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-start gap-x-2 ">
                     <FaCirclePlus className=" w-5 h-5 text-captive-blue mt-2" />
                     <div>
                      <h3 className="text-lg font-semibold">Association ou collectivité</h3>
                      <p className="mb-0">Souhaitant informer et communiquer
                      facilement</p>
                    </div>    
                  </div>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-start gap-x-2 ">
                     <FaCirclePlus className=" w-5 h-5 text-captive-blue mt-2" />
                     <div>
                      <h3 className="text-lg font-semibold">Association ou collectivité</h3>
                      <p className="mb-0">Souhaitant informer et communiquer
                      facilement</p>
                    </div>    
                  </div>
                </li>
              </ul>
            </div> */}
            <div className="grid lg:grid-cols-2 gap-x-10 gap-y-4">
              <ul className="flex flex-col gap-y-4">
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-center gap-x-2">
                    <GrTools className="size-6 text-captive-blue" />
                    <h3 className="text-lg font-semibold">Artisans</h3>
                  </div>     
                  <p className="mb-0">Plombier, électricien, maçon, peintre, menuisier...</p>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs border-b-4 border-captive-blue">
                  <div className="flex items-center gap-x-2">
                     <IoStorefrontOutline className="size-6 text-captive-blue" />                
                    <h3 className="text-lg font-semibold">Commerçant local</h3>
                  </div>
                      <p className="mb-0">Restaurant, salon de coiffure, boutique,
                      fleuriste...</p>    
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-center gap-x-2">
                    <MdOutlineHealthAndSafety className="size-6 text-captive-blue" />
                    <h3 className="text-lg font-semibold">Profession libérale</h3>
                  </div>     
                  <p className="mb-0">Avocat, médecin, architecte, consultant...</p>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-center gap-x-2">
                    <MdOutlineHealthAndSafety className="size-6 text-captive-blue" />
                    <h3 className="font-semibold">Indépendant / auto-entrepreneur</h3>
                  </div>     
                  <p className="mb-0">Coach, photographe,
                      graphiste...</p>
                </li>
              </ul>
              <ul className="flex flex-col gap-y-4">
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-center gap-x-2">
                    <MdOutlineHealthAndSafety className="size-6 text-captive-blue" />
                    <h3 className="text-lg font-semibold">Professionnel du bien-être</h3>
                  </div>     
                  <p className="mb-0">Ostéopathe, naturopathe,
                      esthéticienne...</p>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-center gap-x-2">
                    <MdOutlineHealthAndSafety className="size-6 text-captive-blue" />
                    <h3 className="text-lg font-semibold">TPE / PME</h3>
                  </div>     
                  <p className="mb-0">Souhaitant une présence professionnelle
                      en ligne</p>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-center gap-x-2">
                    <MdOutlineHealthAndSafety className="size-6 text-captive-blue" />
                    <h3 className="text-lg font-semibold">Association ou collectivité</h3>
                  </div>     
                  <p className="mb-0">Souhaitant informer et communiquer
                      facilement</p>
                </li>
                <li className="py-1 w-full bg-white p-4 rounded-lg shadow-xs">
                  <div className="flex items-center gap-x-2">
                    <MdOutlineHealthAndSafety className="size-6 text-captive-blue" />
                    <h3 className="text-lg font-semibold">Association ou collectivité</h3>
                  </div>     
                  <p className="mb-0">Souhaitant informer et communiquer
                      facilement</p>
                </li>
              </ul>
            </div>
          </div>
          <div className="flex justify-end">
            <Image
              src={SiteProfessionnels}
              alt="Logo Shopify"
              className="justify-self-center place-self-center lg:w-[90%]"
              width={800}
              height={800}
              style={{
                maxWidth: "100%",
                height: "auto",
              }}
              priority
            />
          </div>
        </div>
      </section>
      <section className="py-12 px-8 lg:px-32">
        <div className="flex items-center flex-col">
          <span className="heading__span">
            NOTRE ENGAGEMENT
          </span>
          <h2 className="heading__center mb-4">
            Notre accompagnement personnalisé pour votre site vitrine
          </h2>
          <p className="text-lg font-semibold text-center">
            Notre mission : vous livrer un site clé en main, professionnel,
            moderne et facile à gérer.
          </p>
        </div>
        <div className="grid lg:grid-cols-3 lg:gap-x-10 gap-y-10 mt-12 lg:px-28 xl:px-36">
          <div className="bg-captive-primary p-6 rounded-lg shadow-xs border-b-4 border-captive-blue flex flex-col justify-center">
            <div className="flex justify-center mb-6">
              <IconDesign className="fill-captive-blue text-center w-20 h-20" />
            </div>
            <h3 className="text-center text-xl mb-4 text-shikam-normal font-semibold">
              Personnalisation du design du site
            </h3>
            <p className="text-center">
              Nous créons un design sur mesure, adapté à votre image de marque
              pour valoriser votre activité et inspirer confiance à vos
              visiteurs.
            </p>
          </div>
          <div className="bg-captive-primary p-6 rounded-lg shadow-xs border-b-4 border-captive-blue">
            <div className="flex justify-center mb-6">
              <IconPages className="fill-captive-blue text-center w-20 h-20" />
            </div>
            <h3 className="text-center text-xl mb-4 text-shikam-normal font-semibold">
              Création des pages essentielles
            </h3>
            <p className="text-center">
              Nous concevons toutes les pages indispensables pour présenter vos
              services, votre entreprise, vos témoignages, votre équipe ou
              encore vos réalisations.
            </p>
          </div>
          <div className="bg-captive-primary p-6 rounded-lg shadow-xs border-b-4 border-captive-blue">
            <div className="flex justify-center mb-6">
              <IconConfiguration className="fill-captive-blue text-center w-20 h-20" />
            </div>
            <h3 className="text-center text-xl mb-4 text-shikam-normal font-semibold">
              Configuration complète du site
            </h3>
            <p className="text-center">
              Nous configurons tous les éléments techniques : nom de domaine,
              hébergement, sécurité (HTTPS), formulaires de contact, mentions
              légales, RGPD, et autres paramètres essentiels.
            </p>
          </div>
          <div className="bg-captive-primary p-6 rounded-lg shadow-xs border-b-4 border-captive-blue">
            <div className="flex justify-center mb-6">
              <IconSeo className="fill-captive-blue text-center w-20 h-20" />
            </div>
            <h3 className="text-center text-xl mb-4 text-shikam-normal font-semibold">
              Référencement de base (SEO) sur Google
            </h3>
            <p className="text-center">
              Nous optimisons les titres, URLs, balises et contenus pour
              garantir une bonne visibilité de votre site sur Google dès sa mise
              en ligne.
            </p>
          </div>
          <div className="bg-captive-primary p-6 rounded-lg shadow-xs border-b-4 border-captive-blue">
            <div className="flex justify-center mb-6">
              <IconDeployement className="fill-captive-blue text-center w-20 h-20" />
            </div>
            <h3 className="text-center text-xl mb-4 text-shikam-normal font-semibold">
              Mise en ligne de votre site vitrine
            </h3>
            <p className="text-center">
              Une fois tout validé, nous mettons votre site en ligne et le
              rendons accessible au public. Votre entreprise est désormais
              visible 24h/24 sur le web.
            </p>
          </div>
          <div className="bg-captive-primary p-6 rounded-lg shadow-xs border-b-4 border-captive-blue">
            <div className="flex justify-center mb-6">
              <IconTraining className="fill-captive-blue text-center w-20 h-20" />
            </div>
            <h3 className="text-center text-xl mb-4 text-shikam-normal font-semibold">
              Formation à l’utilisation du site
            </h3>
            <p className="text-center">
              Nous vous formons à l’utilisation de votre site (ajout de textes,
              images, pages, etc.), si besoin pour certaines activités, pour que
              vous puissiez le gérer facilement et en toute autonomie.
            </p>
          </div>
        </div>
      </section>
      <section className="my-10 lg:px-40 xl:px-68">
        <div className="bg-captive-secondary flex lg:flex px-10 py-6 items-center justify-between rounded-lg flex-col gap-y-4">
          <h2 className="heading__center text-white mb-2 px-0">
            Prêt à donner de la visibilité à votre activité ?
          </h2>
          <p className="text-white text-center lg:px-20 text-lg">
            Contactez-nous pour discuter de votre projet. Nous réalisonserons un
            site vitrine qui mettra en valeur vos services et vous aidera à
            attirer de nouveaux clients.
          </p>
          <button className="px-8 py-3 rounded-full border-2 bg-captive-primary hover:bg-captive-secondary-hover hover:text-white transition-all duration-75 ease-in-out">
            <Link
              href="tel:0757837110"
              className="flex gap-3 items-center text-lg font-bold"
            >
              <RiWhatsappFill className="h-8 w-8 text-green-700" />
              07 57 83 71 10
            </Link>
          </button>
        </div>
      </section>
    </>
  );
}

export default Page;
