import { Metadata } from "next";
import { PricingCardEcom } from "./pricing-card-ecom";
import { PricingCardVitrine } from "./pricing-card-vitrine";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Page() {
  return (
    <section className="mb-20 px-8 lg:px-32">
      <PricingCardVitrine />
      <PricingCardEcom />
    </section>
  );
}

export default Page;
